### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by anba** [tc39/proposal-async-await#68]
http://tc39.github.io/ecmascript-asyncawait/#status

Stage is now 3.

http://tc39.github.io/ecmascript-asyncawait/#async-decls-exprs-static-semantics-BoundNames

"*" are recognized as markdown instead of plain text.

http://tc39.github.io/ecmascript-asyncawait/#async-arrows-static-semantics-early-errors

"AsyncArrowFunction::CoverCallExpressionAndAsyncArrowHead" needs to handle [Yield], cf. http://tc39.github.io/ecma262/#sec-arrow-function-definitions-static-semantics-early-errors

It's probably not valid to reference "AsyncConciseBody" in "AsyncArrowHead::async[no LineTerminator here]ArrowFormalParameters", because AsyncConciseBody is not part of AsyncArrowHead.

http://tc39.github.io/ecmascript-asyncawait/#async-arrows-EvaluateBody

`functionObject` and `argumentsList` not passed in "AsyncConciseBody::{AsyncFunctionBody}".

http://tc39.github.io/ecmascript-asyncawait/#async-function-prototype-properties

Typo: "prototpe"
Typo: "instrinsic"

**Comment by bterlson** [comment]
Thanks @anba for the great review :) Some questions, if I may...

> "AsyncArrowFunction::CoverCallExpressionAndAsyncArrowHead" needs to handle [Yield], cf. 

Do I need to handle yield specially? I don't see why it is necessary to include the verbage that ES6 has. Specifically, the action taken is same if yield is present or not present, so why not just say... apply the cover grammar with no tokens left over, and apply the yield semantics to the supplemental grammar?

> It's probably not valid to reference "AsyncConciseBody" in "AsyncArrowHead::async[no LineTerminator here]ArrowFormalParameters", because AsyncConciseBody is not part of AsyncArrowHead.

Yeah you're probably right, good catch! I'm not sure how to fix this though - I can't make it a static semantics for `AsyncArrowFunction :: CoverCallExpressionAndAsyncArrowHead => AsyncConciseBody` since  ArrowFormalParameters is from the supplemental grammar. I'd hate to make the grammar less well factored to avoid this issue... Thoughts?

Fixed all the other issues you noted!

**Comment by anba** [comment]
> Yeah you're probably right, good catch! I'm not sure how to fix this though - I can't make it a static semantics for AsyncArrowFunction :: CoverCallExpressionAndAsyncArrowHead => AsyncConciseBody since ArrowFormalParameters is from the supplemental grammar. I'd hate to make the grammar less well factored to avoid this issue... Thoughts?

It should be possible to move all early error checks from _AsyncArrowHead_ to _AsyncArrowFunction_.
  -> https://gist.github.com/anba/ec84fa8d9ed13ee30511

> Do I need to handle yield specially? I don't see why it is necessary to include the verbage that ES6 has. Specifically, the action taken is same if yield is present or not present, so why not just say... apply the cover grammar with no tokens left over, and apply the yield semantics to the supplemental grammar?

Now I wonder whether or not [Yield] is actually needed in _AsyncArrowHead_. Do you know an example where [Yield] is required (when the early errors checks are already applied to _CoverCallExpressionAndAsyncArrowHead_ per the gist from above)?

**Comment by bterlson** [comment]
> It should be possible to move all early error checks from AsyncArrowHead to AsyncArrowFunction.
>  -> https://gist.github.com/anba/ec84fa8d9ed13ee30511

I see, I was thinking yesterday this wouldn't work because in some contexts CoverCallExpressionAndAsyncArrowHead is allowed to contain yield but attaching these semantics to AsyncArrowFunction seems fine I agree.

> Now I wonder whether or not [Yield] is actually needed in AsyncArrowHead. Do you know an example where [Yield] is required (when the early errors checks are already applied to CoverCallExpressionAndAsyncArrowHead per the gist from above)?

I believe that it is needed because an async arrow not nested in a generator should allow yield-as-identifier so the static semantics would not cause an error in that case. Only when the parameter is present (ie. when the async arrow is in a generator body) should those static semantics create an error. Probably I'm missing something though.

**Comment by bterlson** [comment]
@anba want to give that gist as a PR? I can pull it in too but it's easier to track your contributions if you send a PR :)

**Comment by anba** [comment]
> @anba want to give that gist as a PR? I can pull it in too but it's easier to track your contributions if you send a PR :)

Just created PR #69

> I believe that it is needed because an async arrow not nested in a generator should allow yield-as-identifier so the static semantics would not cause an error in that case. Only when the parameter is present (ie. when the async arrow is in a generator body) should those static semantics create an error. Probably I'm missing something though.

Here's my reasoning why _[Yield]_ is not required for _AsyncArrowHead_:

When the `yield` token is present in _CoverCallExpressionAndAsyncArrowHead[Yield]_, one of the following productions gets parsed:
- **_IdentifierReference**_
  - Throws a SyntaxError because of 12.1.1:

> IdentifierReference[Yield] : Identifier
> - It is a Syntax Error if this production has a [Yield] parameter and StringValue of Identifier is "yield".
- **_BindingIdentifier**_
  - Throws a SyntaxError because of 12.1.1:

> BindingIdentifier[Yield] : Identifier
> - It is a Syntax Error if this production has a [Yield] parameter and StringValue of Identifier is "yield".
- **_YieldExpression**_
  - Throws a SyntaxError because of:

> AsyncArrowFunction
> - It is a Syntax Error if CoverCallExpressionAndAsyncArrowHead Contains YieldExpression is true. 

That means `yield` is already rejected when parsing the initial _CoverCallExpressionAndAsyncArrowHead[Yield]_ and therefore it should not be necessary to propagate _[Yield]_ to _AsyncArrowHead_.

**Comment by bterlson** [comment]
Alright, I agree with you!

**Comment by bterlson** [comment]
This should all be addressed now. Thanks @anba!!!

**Comment by anba** [comment]
Removing [Yield] in AsyncArrowHead is still an open issue. I'll try to create a PR for this later today.

**Comment by bterlson** [comment]
@anba I think it's fixed, unless I misunderstand what you mean. See d3a5143.

**Comment by anba** [comment]
Ah, I didn't see that commit. Sorry for the confusion!

(You forgot to update [CoveredAsyncArrowHead](https://tc39.github.io/ecmascript-asyncawait/#async-arrows-static-semantics-CoveredAsyncArrowHead). :wink: )

**Comment by bterlson** [comment]
Whoops, will do it! Sorry :(
